name: Excelsior

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=3.10.5 <4.0.0"

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter
  collection: any
  async: any
  meta: any

  # Localization
  intl: 0.18.1
  flutter_localizations:
    sdk: flutter

  # Stream
  stream_transform: 2.1.0
  rxdart: 0.27.7

  # BLoC
  flutter_bloc: 8.1.3

  # Networking
  dio: 5.3.3

  # Persisting
  shared_preferences: 2.2.2

  # Logging
  stack_trace: 1.11.0
  sentry_flutter: 7.11.0
  logging: 1.2.0

  # Utils
  pure: 0.2.0
  platform_info: 4.0.2
  bloc_concurrency: 0.2.2
  path: 1.8.3
  path_provider: 2.1.0
  flutter_native_splash: 2.3.5

dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter

  # Lints
  flutter_lints: ^2.0.0

  # Utils
  flutter_gen_runner: 5.3.2
  flutter_launcher_icons: 0.13.1
  melos: 3.2.0
  intl_utils: 2.8.5

flutter:
  uses-material-design: true

  generate: false


flutter_gen:
  output: lib/src/core/assets/generated
  line_length: 80

flutter_intl:
  enabled: true
  class_name: GeneratedLocalization
  main_locale: en
  arb_dir: lib/src/core/localization/translations
  output_dir: lib/src/core/localization/generated